apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: <APP_NAME>
  namespace: <NAMESPACE>
spec:
  template:
    spec:
      containers:
        - image: <DOCKER_REPO>
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
